version: "3.8"

services:
  web:
    build: .
    container_name: ai-healthcare-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ai-healthcare-db
    environment:
      POSTGRES_USER: health_user
      POSTGRES_PASSWORD: health_pass
      POSTGRES_DB: healthcare
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
