version: 2
updates:
  # 前端依赖更新 - 只在main分支
  - package-ecosystem: "npm"
    directory: "/src/front"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "main"
    open-pull-requests-limit: 5
    reviewers:
      - "cs673a2f25team2"
    assignees:
      - "cs673a2f25team2"
    commit-message:
      prefix: "npm"
      include: "scope"
    
  # 前端health-frontend依赖更新 - 只在main分支
  - package-ecosystem: "npm"
    directory: "/src/front/health-frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "main"
    open-pull-requests-limit: 5
    reviewers:
      - "cs673a2f25team2"
    assignees:
      - "cs673a2f25team2"
    commit-message:
      prefix: "npm"
      include: "scope"
    
  # 后端Maven依赖更新 - 只在main分支
  - package-ecosystem: "maven"
    directory: "/src/back"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "main"
    open-pull-requests-limit: 5
    reviewers:
      - "cs673a2f25team2"
    assignees:
      - "cs673a2f25team2"
    commit-message:
      prefix: "maven"
      include: "scope"